services:
  backend:
    build: ./backend
    ports:
      - "7091:7091"
    networks:
      - app-network
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - app-network
    volumes:
      - /app/node_modules
      - ./frontend/search-app:/app

networks:
  app-network: