services:
  backend:
    build: ./backend
    ports:
      - "7091:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=SearchDb;User Id=sa;Password=Your_password123;TrustServerCertificate=True
    depends_on:
      - sqlserver
    networks:
      - app-network
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network
    volumes:
      - /app/node_modules
      - ./frontend/search-app:/app
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Your_password123
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    networks:
      - app-network

networks:
  app-network: